spring:
  #分库分表配置
  shardingsphere:
    datasource:
      #多个用英文逗号隔开
      names: ds0,ds1
      ds0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/sharding-jdbc1?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
        username: root
        password: wk123456
      ds1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/sharding-jdbc2?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
        username: root
        password: wk123456
    #配置分库分表规则
    sharding:
      tables:
        #用户表 逻辑表名
        user:
          #真实表 ds0.user_0
          #${begin..end}表示范围区间
          #${[unit1, unit2, unit_x]}表示枚举值
          actualDataNodes: ds$->{0..1}.user_$->{0..2}
          #对应的逻辑表
          logicTable: user
          #分库策略
          databaseStrategy:
            #行表达式策略 需符合groovy语法
            inline:
              #分片列名称
              shardingColumn: id
              #分片算法行表达式
              algorithmExpression: ds$->{id % 2}
          #分表规则
          tableStrategy:
            inline:
              algorithmExpression: user_$->{id % 3}
              shardingColumn: id
          #分布式id
          keyGenerator:
            column: id
            type: SNOWFLAKE
        t_order:
          actualDataNodes: ds$->{0..1}.t_order_$->{0..3}
          databaseStrategy:
            inline:
              algorithmExpression: ds$->{user_id % 2}
              shardingColumn: user_id
          logicTable: t_order
          tableStrategy:
            #标准分片算法 SQL 语句中有>，>=, <=，<，=，IN 和 BETWEEN AND 操作符，都可以应用此分片策略
            standard:
              #精确分片算法类名称
              preciseAlgorithmClassName: com.harmony.shardingjdbc.sharding.algorithm.PreciseTableShardingAlgorithm
              shardingColumn: order_id
              #范围分片算法类名称，用于BETWEEN，可选
              #rangeAlgorithmClassName: com.harmony.shardingjdbc.sharding.algorithm.RangeTableShardingAlgorithm
              #Hint分片策略
              #hint:
              #Hint分片算法类名称
              #algorithmClassName: com.harmony.shardingjdbc.sharding.algorithm.HintTableShardingAlgorithm
              #complex:
              #分片列名称，多个列以逗号分隔
              #shardingColumns: user_id,order_id
              #复合分片算法类名称。该类需实现ComplexKeysShardingAlgorithm接口并提供无参数的
              #algorithmClassName: com.harmony.shardingjdbc.sharding.algorithm.RangeTableShardingAlgorithm


          keyGenerator:
            column: order_id
            type: SNOWFLAKE
        order_item:
          actualDataNodes: ds$->{0..1}.order_item_$->{0..3}
          databaseStrategy:
            inline:
              algorithmExpression: ds$->{user_id % 2}
              shardingColumn: user_id
          logicTable: order_item
          tableStrategy:
            inline:
              algorithmExpression: order_item_$->{order_id % 4}
              shardingColumn: order_id
      #绑定关系表
      binding-tables:
        - t_order,order_item
      #广播表
      broadcastTables:
        - user_config
      #默认使用雪花算法生成分布式ID
      default-key-generator:
        column: id
        type: SNOWFLAKE
    props:
      #日志显示SQL
      sql.show: true
