
spring:
  datasource:
    # 动态数据源配置
    dynamic:
      datasource:
        master:
          type: com.alibaba.druid.pool.DruidDataSource
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:3306/no_sharding?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
          username: root
          password: wk123456
      primary: master
  profiles:
    active: sharding-jdbc

logging:
  level:
    com:
      github:
        dudiao:
          sharding: debug
#mybatis-plus配置
mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
    # use-generated-keys: true
    default-fetch-size: 100
    default-statement-timeout: 30